import type { Metadata } from "next";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <NextTopLoader
          color="#EFC162"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #EFC162,0 0 5px #EFC162"
        />

        {children}
      </body>
    </html>
  );
}
